AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'app/services/github_service.rb'

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/LineLength:
  Max: 120
